### ISSUE TITLE
vs 2017 can not link to libtiff.lib

### ISSUE THREAD

**Issue by frankyifei** [LuxCoreRender/WindowsCompileDeps#2]
Got this error when compile with newest VS 2017

>LINK : fatal error C1047: The object or library file 'D:\code\WindowsCompileDeps\x64\Release\lib\libtiff.lib' was created with an older compiler than other objects; rebuild old objects and libraries [D:\code\WindowsCompile\Build_
       CMake\LuxCore\tests\luxcoreimplserializationdemo\luxcoreimplserializationdemo.vcxproj]

**Comment by Dade916** [comment]
We were working on VS2017 support, we should have fixed all problems left few minutes ago. Can you re-try after having updated all repositories ?
